"""ROCm-specific setup and environment variable configuration."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

from forge.hardware.detect import GPUInfo
from forge.utils.logging import get_logger

log = get_logger("hardware.rocm")

# Known GFX version overrides for AMD APUs/GPUs that need HSA_OVERRIDE_GFX_VERSION.
# Maps device IDs or architecture names to the required GFX version.
GFX_OVERRIDES: dict[str, str] = {
    # RDNA2 APUs (Rembrandt, Barcelo, etc.)
    "gfx1035": "10.3.0",
    "gfx1036": "10.3.0",
    # RDNA3 APUs (Phoenix, Hawk Point)
    "gfx1103": "11.0.0",
    # RDNA2 discrete
    "gfx1030": "10.3.0",
    "gfx1031": "10.3.0",
    "gfx1032": "10.3.0",
    # RDNA3 discrete
    "gfx1100": "11.0.0",
    "gfx1101": "11.0.0",
    "gfx1102": "11.0.0",
}


def configure_rocm_env(gpu: GPUInfo) -> dict[str, str]:
    """Set ROCm environment variables for optimal Ollama performance.

    Returns a dict of environment variables that were set.
    """
    env_vars: dict[str, str] = {}

    if gpu.vendor != "amd" or gpu.driver != "rocm":
        return env_vars

    # HSA_OVERRIDE_GFX_VERSION — needed for many AMD GPUs
    gfx_version = _detect_gfx_override(gpu)
    if gfx_version:
        os.environ.setdefault("HSA_OVERRIDE_GFX_VERSION", gfx_version)
        env_vars["HSA_OVERRIDE_GFX_VERSION"] = gfx_version
        log.info("Set HSA_OVERRIDE_GFX_VERSION=%s", gfx_version)

    # Flash attention — significant speedup on supported hardware
    os.environ.setdefault("OLLAMA_FLASH_ATTENTION", "1")
    env_vars["OLLAMA_FLASH_ATTENTION"] = "1"

    # Max loaded models — prevent OOM on iGPUs
    if gpu.is_igpu:
        os.environ.setdefault("OLLAMA_MAX_LOADED_MODELS", "1")
        env_vars["OLLAMA_MAX_LOADED_MODELS"] = "1"
    else:
        os.environ.setdefault("OLLAMA_MAX_LOADED_MODELS", "2")
        env_vars["OLLAMA_MAX_LOADED_MODELS"] = "2"

    return env_vars


def _detect_gfx_override(gpu: GPUInfo) -> str:
    """Detect the required HSA_OVERRIDE_GFX_VERSION for this GPU."""
    # Check if already set by user
    existing = os.environ.get("HSA_OVERRIDE_GFX_VERSION")
    if existing:
        return existing

    # Try to detect GFX version from rocminfo
    gfx = _get_gfx_from_rocminfo()
    if gfx and gfx in GFX_OVERRIDES:
        return GFX_OVERRIDES[gfx]

    # Try architecture field from detection
    if gpu.architecture:
        for prefix, override in GFX_OVERRIDES.items():
            if gpu.architecture.startswith(prefix):
                return override

    return ""


def _get_gfx_from_rocminfo() -> str:
    """Extract GFX target from rocminfo output."""
    try:
        result = subprocess.run(
            ["rocminfo"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            match = re.search(r"Name:\s+(gfx\d+)", result.stdout)
            if match:
                return match.group(1)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return ""


def get_rocm_status() -> dict[str, str]:
    """Get current ROCm status for display."""
    status: dict[str, str] = {}

    # ROCm version
    version_file = Path("/opt/rocm/.info/version")
    if version_file.exists():
        status["rocm_version"] = version_file.read_text().strip()
    else:
        status["rocm_version"] = "not installed"

    # Current env vars
    for var in ["HSA_OVERRIDE_GFX_VERSION", "OLLAMA_FLASH_ATTENTION", "OLLAMA_MAX_LOADED_MODELS"]:
        val = os.environ.get(var)
        if val:
            status[var] = val

    # User groups
    try:
        result = subprocess.run(["groups"], capture_output=True, text=True, timeout=5)
        groups = result.stdout.strip().split()
        status["render_group"] = "yes" if "render" in groups else "no"
        status["video_group"] = "yes" if "video" in groups else "no"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return status


def generate_ollama_service_env(gpu: GPUInfo) -> str:
    """Generate environment variables for Ollama systemd service override."""
    lines = ["# Generated by ollama-forge for optimal ROCm performance"]

    gfx = _detect_gfx_override(gpu)
    if gfx:
        lines.append(f'Environment="HSA_OVERRIDE_GFX_VERSION={gfx}"')

    lines.append('Environment="OLLAMA_FLASH_ATTENTION=1"')

    max_models = "1" if gpu.is_igpu else "2"
    lines.append(f'Environment="OLLAMA_MAX_LOADED_MODELS={max_models}"')

    return "\n".join(lines)
